### ISSUE TITLE
how to apply this code for document summary generate？

### ISSUE THREAD

**Issue by FlandrinorZXY** [TobiasLee/SeqGAN_Poem#3]
1. i used 268 poem to train model and get 896 generated_poem, but i can't figure out the relationship between the number 268 and 896. so what happend in this generate procession?
2. maybe i can mark every keyword with a number, just like u marked every word with a unique number, and then put them together as a sequence, and then... i have no idea about how to go on with it... so any suggestion for this issue?

**Comment by TobiasLee** [comment]
1. The generate num is defined in function `generation_sample`. Since the generator produces samples by batches, so the final result is multiple times of batch size.

2. The preprocessing of you data is different, like char-level v.s word-level. As long as  you have a uniform representation of the sequence (like, all in keyword level), then you can feed it into the model.

**Comment by FlandrinorZXY** [comment]
1. thx for your reply.
2. in fact I want to generate the summary with  news, but news are not like poems, their summary may be sequence with different length, and also the sequences i feed into model have different length too.
maybe i can set a max length L which is much longer than sequence as the batchsize, when i feed a sequence into model i can pad some ‘  ’ to satisfy the length request, and maybe i can get a output sequence with some '  ' too?
 is it a good idea?

**Comment by TobiasLee** [comment]
1. Glad to be helpful.
2. Well, padding the input to a fix max length is a common practice in text generation. You may also append a `<EOS>` token to the end of each summary as a mark of ending. As well as the generator generate a `<EOS>` token, the process can stop to improve efficiency.

**Comment by FlandrinorZXY** [comment]
1. I found your blog about chinese hiphop lyrics generator, It's so Inspiring. Some lyrics generated by model are much more intelengient than human's creation. I'm thinking about a trick model with sentence2vec, based on your blog and this project to generate the  summary of news, although it's a big challenge for me a newbee in NLP field.
2. Looking forward your new blog with nice content.

**Comment by TobiasLee** [comment]
Thanks and good luck ~
