### ISSUE TITLE
output of Discriminator D

### ISSUE THREAD

**Issue by Arkamnd** [TobiasLee/SeqGAN_Poem#4]

**Comment by Arkamnd** [comment]
Hello Tobias, one question. How can I get the the results of the discriminator. i.e if I want to compute the ROC. Thank you.

**Comment by TobiasLee** [comment]
Hi, you can add come attributes in the discriminator like : 
`self.roc = the_computation_you_need` and fetch the attribute like `D.roc` when training.

**Comment by Arkamnd** [comment]
Thank you Tobias!
